---
title: "Publications"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}
</style>

<div class="row" style="text-align: justify; font-size:15px;  text-justify: inter-word; padding-top: 20px;padding-left: 20px;padding-right: 20px">

Liu, C., Casper, R., Aguirre-Muñoz, Z. (under review). The Cognitive Architecture of College Reading: How Attention, Executive Function, and Metacognitive Awareness Shape Comprehension.

Aguirre-Muñoz, Z., Liu, C., & Casper, R. (2025). Elevating Elementary Teacher Practice in the English Learner Writing Classroom with SFL Metalanguage and Translanguaging Approaches. In Teaching Writing to English Language Learners in the Elementary Classroom (pp. 31-55). Routledge.

Aguirre-Muñoz, Z., Pando, M., & Liu, C. (2024). Enhancing Bilingual/ESL Teachers’ STEM Instruction with Targeted Content and Disciplinary Literacy Professional Development: A Study on Knowledge and Practice Outcomes. Education Sciences, 14(7), 745.

Liu, C., Ryskin, R., Aguirre-Muñoz, Z. (in preparation). Effects of context and proficiency on processing difficulty during L2 reading

Aguirre-Muñoz, Z., Liu, C., Casper, R., L, Shan. (under review). Enhancing College Text Comprehension Through Brief Metalinguistic Training. 
